version: "3"
services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: portfolio-blog-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - portfolio-blog

    # Nginx Service
    nginx:
        image: nginx:alpine
        container_name: portfolio-blog-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        networks:
            - portfolio-blog

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: portfolio-blog-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: portfolio_blog_db
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_PASSWORD: userpassword
            MYSQL_USER: admin
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - portfolio-blog

networks:
    portfolio-blog:
        driver: bridge

volumes:
    dbdata:
        driver: local
